/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author casso
 */
public class jfPesquisa extends javax.swing.JFrame {

    /**
     * Creates new form jfPesquisa
     */
    public jfPesquisa() {
        initComponents();
    }
    
    private void verChk() {
        String msg = "Linguagens: \n";
        int countChk = 0;
        if (chkCobol.isSelected()) {
            msg = msg + chkCobol.getText() + "\n";
            countChk++;
        }
        if (chkJava.isSelected()) {
            msg = msg + chkJava.getText() + "\n";
            countChk++;
        }
        if (chkPHP.isSelected()) {
            msg = msg + chkPHP.getText() + "\n";
            countChk++;
        }
        if (chkPy.isSelected()) {
            msg = msg + chkPy.getText() + "\n";
            countChk++;
        }
        if (countChk > 0) {
            JOptionPane.showMessageDialog(null, msg);
        } else {
            JOptionPane.showMessageDialog(null, "nenhuma linguagem selecionada", ".:Linguagens:.", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void limparChk(){
        chkCobol.setSelected(false);
        chkJava.setSelected(false);
        chkPHP.setSelected(false);
        chkPy.setSelected(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEstadoCivil = new javax.swing.ButtonGroup();
        bgPagamento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chkJava = new javax.swing.JCheckBox();
        chkPHP = new javax.swing.JCheckBox();
        chkPy = new javax.swing.JCheckBox();
        chkCobol = new javax.swing.JCheckBox();
        btnChk = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jcbLinguagens = new javax.swing.JComboBox<>();
        btnCB = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jrbSolteiro = new javax.swing.JRadioButton();
        jrbCasado = new javax.swing.JRadioButton();
        jrbSeparado = new javax.swing.JRadioButton();
        jrbDivorciado = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jrbUniaoEstavel = new javax.swing.JRadioButton();
        btnRb = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jrbBoleto = new javax.swing.JRadioButton();
        jrbCartão = new javax.swing.JRadioButton();
        jrbPix = new javax.swing.JRadioButton();
        jrbPayPal = new javax.swing.JRadioButton();
        btnRbEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Estado Civil?");

        chkJava.setText("Java");

        chkPHP.setText("PHP");

        chkPy.setText("Python");

        chkCobol.setText("Cobol");

        btnChk.setText("Enviar");
        btnChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChkActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Qual linguagem não conhece?");

        jcbLinguagens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Cobol", "Fortran", "Assembler", "C#", "C++", "R", "Rust", "Ruby" }));

        btnCB.setText("Enviar");
        btnCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCBActionPerformed(evt);
            }
        });

        bgEstadoCivil.add(jrbSolteiro);
        jrbSolteiro.setText("Solteiro(a)");

        bgEstadoCivil.add(jrbCasado);
        jrbCasado.setText("Casado(a)");

        bgEstadoCivil.add(jrbSeparado);
        jrbSeparado.setText("Separado(a)");

        bgEstadoCivil.add(jrbDivorciado);
        jrbDivorciado.setText("Divorciado(a)");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Quais linguagem já programou?");

        bgEstadoCivil.add(jrbUniaoEstavel);
        jrbUniaoEstavel.setText("União Estável");

        btnRb.setText("Enviar");
        btnRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Formas De Pagamento");

        bgPagamento.add(jrbBoleto);
        jrbBoleto.setText("Boleto");

        bgPagamento.add(jrbCartão);
        jrbCartão.setText("Cartão");

        bgPagamento.add(jrbPix);
        jrbPix.setText("Pix");

        bgPagamento.add(jrbPayPal);
        jrbPayPal.setText("PayPal");

        btnRbEnviar.setText("Enviar");
        btnRbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRbEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRbEnviar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCB, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbLinguagens, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jSeparator3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkJava)
                                    .addComponent(chkPy)
                                    .addComponent(chkCobol)
                                    .addComponent(chkPHP)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jrbSolteiro)
                                        .addComponent(jrbCasado)
                                        .addComponent(jrbSeparado)
                                        .addComponent(jrbDivorciado)
                                        .addComponent(jrbUniaoEstavel))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRb)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnChk)
                                .addGap(18, 18, 18)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbBoleto)
                            .addComponent(jrbPayPal)
                            .addComponent(jrbPix)
                            .addComponent(jrbCartão))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jcbLinguagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(chkJava)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPHP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkCobol)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jrbSolteiro)
                    .addComponent(jrbBoleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jrbCartão)
                    .addComponent(jrbCasado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jrbPix)
                    .addComponent(jrbSeparado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jrbPayPal)
                    .addComponent(jrbDivorciado))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnRbEnviar)
                    .addComponent(btnRb))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jrbUniaoEstavel)
                .addGap(8, 8, 8))
            .addComponent(jSeparator1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCBActionPerformed
        // TODO add your handling code here:
        if (!jcbLinguagens.getSelectedItem().equals("Selecione...")) {
            JOptionPane.showMessageDialog(null, "linguagem de programação selecionada foi: " + jcbLinguagens.getSelectedItem());
        } else {
            JOptionPane.showMessageDialog(null, "selecione uma linguagem");
        }
        jcbLinguagens.setSelectedIndex(0);
    }//GEN-LAST:event_btnCBActionPerformed

    private void btnChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChkActionPerformed
        // TODO add your handling code here:
        verChk();
        limparChk();
    }//GEN-LAST:event_btnChkActionPerformed

    private void btnRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRbActionPerformed
        // TODO add your handling code here:
        for (Enumeration<AbstractButton> btn =bgEstadoCivil.getElements();btn.hasMoreElements();){
          AbstractButton rb = btn.nextElement();
          if(rb.isSelected()){
              JOptionPane.showMessageDialog(this,"Seu estaddo civil é: "+rb.getText());
          }
        }
        bgEstadoCivil.clearSelection();
    }//GEN-LAST:event_btnRbActionPerformed

    private void btnRbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRbEnviarActionPerformed
        // TODO add your handling code here:
       for (Enumeration<AbstractButton> btn =bgPagamento.getElements();btn.hasMoreElements();){
          AbstractButton rb = btn.nextElement();
          if(rb.isSelected()){
              JOptionPane.showMessageDialog(this,"Forma de pagamento selecionada: "+rb.getText());
          }
        }
       bgPagamento.clearSelection();
    }//GEN-LAST:event_btnRbEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEstadoCivil;
    private javax.swing.ButtonGroup bgPagamento;
    private javax.swing.JButton btnCB;
    private javax.swing.JButton btnChk;
    private javax.swing.JButton btnRb;
    private javax.swing.JButton btnRbEnviar;
    private javax.swing.JCheckBox chkCobol;
    private javax.swing.JCheckBox chkJava;
    private javax.swing.JCheckBox chkPHP;
    private javax.swing.JCheckBox chkPy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> jcbLinguagens;
    private javax.swing.JRadioButton jrbBoleto;
    private javax.swing.JRadioButton jrbCartão;
    private javax.swing.JRadioButton jrbCasado;
    private javax.swing.JRadioButton jrbDivorciado;
    private javax.swing.JRadioButton jrbPayPal;
    private javax.swing.JRadioButton jrbPix;
    private javax.swing.JRadioButton jrbSeparado;
    private javax.swing.JRadioButton jrbSolteiro;
    private javax.swing.JRadioButton jrbUniaoEstavel;
    // End of variables declaration//GEN-END:variables
}
