/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.year;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author casso
 */
public class Vida extends javax.swing.JFrame {

    /**
     * Creates new form Vida
     */
    public Vida() {
        initComponents();
    }

    public void limparJTF() {
        jtfSNome.setText("");
        jtfIData.setText("");
        jtfSNome.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfSNome = new javax.swing.JTextField();
        jtfIData = new javax.swing.JTextField();
        jbCalc = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Data de nascimento");

        jtfSNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSNomeActionPerformed(evt);
            }
        });
        jtfSNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSNomeKeyTyped(evt);
            }
        });

        jtfIData.setToolTipText("aaaa-mm-dd");
        jtfIData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfIDataFocusLost(evt);
            }
        });
        jtfIData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIDataActionPerformed(evt);
            }
        });
        jtfIData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIDataKeyTyped(evt);
            }
        });

        jbCalc.setText("Calcular");
        jbCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfSNome, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfIData, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbCalc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbLimpar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfIData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCalc)
                    .addComponent(jbLimpar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIDataActionPerformed

    private void jtfSNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSNomeActionPerformed

    private void jtfSNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSNomeKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321!@#$%¨&*()_+-={}[]/?;:|";
        if (caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfSNomeKeyTyped

    private void jbCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcActionPerformed
        // TODO add your handling code here:
        String nome, msg;
        nome = jtfSNome.getText();
        String dateBeforeString = jtfIData.getText();

        //DateTimeFormatter dtBr= DateTimeFormatter.ofPattern("dd/MM/yyyy");
        //dateBeforeString = LocalDate.parse(dateBeforeString,dtBr);
        try{
        LocalDate dateBefore = LocalDate.parse(dateBeforeString);
        LocalDate dateAfter = LocalDate.now();
        long noOfDaysBetween = ChronoUnit.DAYS.between(dateBefore, dateAfter);
        //System.out.println(noOfDaysBetween);
        if (noOfDaysBetween < 0) {
            JOptionPane.showMessageDialog(this, "Você não é o Marty McFly, por favor escolha uma data do passado!");
            jtfIData.requestFocus();
        }else{
              msg = nome + " voce ja viveu " + noOfDaysBetween + " dias";
        JOptionPane.showMessageDialog(this, msg);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"houve um erro ao calcular: "+e.getMessage()+ "\n Formato esperado: aaaa/mm/dd");
        }
    }//GEN-LAST:event_jbCalcActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limparJTF();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtfIDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIDataKeyTyped
        // TODO add your handling code here:
        String keyText = "0123456789-";
        if (!keyText.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfIDataKeyTyped

    private void jtfIDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfIDataFocusLost
        // TODO add your handling code here:
        if (jtfIData.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Revise a data informada!");
            jtfIData.requestFocus();
        }
    }//GEN-LAST:event_jtfIDataFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vida().setVisible(true);
            }
        });
    }
    //Date data = new Date();
    //data = Date.parseDate(jtfIData.getText());
    //SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); 
    //data = formato.parse(jtfIData.getText());
    //DateTimeFormatter dtBrasil = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbCalc;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JTextField jtfIData;
    private javax.swing.JTextField jtfSNome;
    // End of variables declaration//GEN-END:variables
}
